name: CI

on: [push] 

jobs:
   dotnet-template-azure-iot-edge-module:
    name: dotnet-template-azure-iot-edge-module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p .nuget
      - name: Download nuget
        run:  
          wget -O .nuget/nuget.exe
          https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
      - name: Install Nugget
        run: mono .nuget/nuget.exe
      - name: dotnet test
        run: dotnet test Test/Test.csproj
      - name: nuget packag  
        run: mono .nuget/nuget.exe pack -NoDefaultExcludes
      - name: GitHub Release
        if: |
           success() &&
           startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
            files: ./**/*.nupkg   
       
